openapi: 3.0.3
info:
  title: Shift - Controle Orçamentos de Procedimentos
  description: |-
    Esta é a documentação da API relativa ao desafio técnico do processo seletivo para a vaga de Analista Desenvolvedor Web da Shift.
    <p>
    Contempla dois Endpoints de um <b>Controle de Orçamentos de Procedimentos</b>, especificamente o de <b>Gestão de Orçamento</b> e <b>Itens do Orçamento</b>.

  contact:
    email: ronaldorbc@hotmail.com
  version: 1.0.0
#servers:
#  - url: http://localhost:8080/
tags:
  - name: Orcamento
    description: Gerencia o cadastro dos orçamentos de procedimentos
  - name: ItemOrcamento
    description: Gerencia os items contidos nos orçamentos de procedimentos
paths:
  /orcamento:
    post:
      tags:
        - Orcamento
      summary: Cria um novo orçamento
      description: Cria uma nova solicitação de orçamento de procedimentos
      operationId: adicionaOrcamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orcamento'
        required: true
      responses:
        '200':
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orcamento'
        '400':
          description: Problema nos parametros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '422':
          description: Problema de validação da requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    put:
      tags:
        - Orcamento
      summary: Atualiza um orçamento
      description: Atualiza um orçamento pelo ID
      operationId: atualizaOrcamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orcamento'
        required: true
      responses:
        '200':
          description: Cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orcamento'
        '400':
          description: Problema nos parametros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Orçamento não encontrado
        '422':
          description: Problema ao processar requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    get:
      tags:
        - Orcamento
      summary: Retorna os orçamentos por Fonte Pagadora ou Pessoa Física
      description: Retorna uma lista de orçamentos relativos a uma Fonte Pagadora ou Pessoa Física, os dois filtro podem ser utilizados ao mesmo tempo. <b>Pelo menos um deles deve ser diferente de zero.</b>
      operationId: procuraOrcamentoPorFonteOuPessoa
      parameters:
        - name: idFonte
          in: query
          description: Id da Fonte Pagadora
          required: true
          schema:
            type: integer
            default: 0
        - name: idPessoa
          in: query
          description: Id da Pessoa Física
          required: true
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Retornado com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Orcamento'
        '400':
          description: Parâmetros inválidos
  /orcamento/{idOrcamento}:
    get:
      tags:
        - Orcamento
      summary: Retorna um orçamento pelo Id
      operationId: pocuraOrcamentoPorId
      parameters:
        - name: idOrcamento
          in: path
          description: Id do Orçamento
          required: true
          schema:
            type: integer
            format: int64
            default: 0
      responses:
        '200':
          description: Retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orcamento'
        '400':
          description: Id inválido
        '404':
          description: Orçamento não encontrado
    delete:
      tags:
        - Orcamento
      summary: Apaga um Orçamento
      operationId: apagaOrcamento
      parameters:
        - name: idOrcamento
          in: path
          description: Id do Orçamento
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Excluído com sucesso
        '400':
          description: Id inválido
        '404':
          description: Orçamento não encontrado
  /itemOrcamento:
    post:
      tags:
        - ItemOrcamento
      summary: Adiciona um novo item em um orçamento de procedimentos
      description: Adiciona um novo item em um orçamento de procedimentos
      operationId: adicionaItemOrcamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemOrcamento'
        required: true
      responses:
        '200':
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemOrcamento'
        '400':
          description: Problema nos parametros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '422':
          description: Problema de validação da requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    put:
      tags:
        - ItemOrcamento
      summary: Atualiza um item de orçamento
      description: Atualiza um item de orçamento pelo ID
      operationId: atualizaItemOrcamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemOrcamento'
        required: true
      responses:
        '200':
          description: Cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemOrcamento'
        '400':
          description: Problema nos parametros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: Item de Orçamento não encontrado
        '422':
          description: Problema ao processar requisição
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
    get:
      tags:
        - ItemOrcamento
      summary: Retorna os itens de um orçamento específico
      operationId: procuraItensOrcamentoPorOrcamento
      parameters:
        - name: idOrcamento
          in: query
          description: Id do Orçamento
          required: true
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Retornado com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemOrcamentoRetorno'
        '400':
          description: Parâmetros inválidos
  /itemOrcamento/{idItemOrcamento}:
    get:
      tags:
        - ItemOrcamento
      summary: Retorna um Item de Orçamento pelo Id
      operationId: pocuraItemOrcamentoPorId
      parameters:
        - name: idItemOrcamento
          in: path
          description: Id do Orçamento
          required: true
          schema:
            type: integer
            format: int64
            default: 0
      responses:
        '200':
          description: Retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemOrcamentoRetorno'
        '400':
          description: Id inválido
        '404':
          description: Orçamento não encontrado
    delete:
      tags:
        - ItemOrcamento
      summary: Apaga um Item do Orçamento
      operationId: apagaItemOrcamento
      parameters:
        - name: idItemOrcamento
          in: path
          description: Id do Item de Orçamento
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Excluído com sucesso
        '400':
          description: Problema na requisição
        '404':
          description: Item de Orçamento não encontrado
components:
  schemas:
    Orcamento:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        descricao:
          type: string
          example: Orçamento para cirugia de hérnia inguinal bilateral do paciente X
        dataValidade:
          type: string
          format: date-time
          example: 2024-11-23T18:25:43.511Z
        valorDesconto:
          type: number
          format: double
          example: 220.5
        idFontePagadora:
          type: integer
          format: int64
          example: 1323456
        idPessoaFisica:
          type: integer
          format: int64
          example: 20334667
        status:
          type: string
          description: Status do Orçamento
          default: EmAnalise
          enum:
            - EmAnalise
            - Aprovado
            - NaoAprovado
        finalizado:
          type: boolean
    ItemOrcamento:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        idItem:
          type: integer
          format: int64
          example: 10
        observacao:
          type: string
          example: Exemplo de obervação
        valor:
          type: number
          format: double
          example: 220.5
        valorDesconto:
          type: number
          format: double
          example: 50.5
        qtde:
          type: integer
          format: int64
          example: 1
        idOrcamento:
          type: integer
          format: int64
          example: 1323456
    Item:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        descricao:
          type: string
        categoria:
          type: string
          enum:
            - Procedimento
            - Adicional
        tipo:
          type: string
    ItemOrcamentoRetorno:
      allOf:
        - $ref: "#/components/schemas/ItemOrcamento"
        - type: object
          properties:
            item:
              $ref: '#/components/schemas/Item'
    ApiResponse:
      type: object
      properties:
        code:
          type: string
        type:
          type: string
        message:
          type: string
